### ISSUE TITLE
Clipper/Docker Integration Roadmap

### ISSUE THREAD

**Issue by gtfierro** [gtfierro/modelserver#1]
Methods to debug
- [ ] `get_clipper_logs`: throws some error (unidentified header?) right now

Methods to implement about stopping models:
- [ ] `stop_versioned_models`
- [ ] `stop_inactive_model_versions`
- [ ] `stop_models`
- [ ] `stop_all_model_containers`
- [ ] `stop_all`

Implementation of the "stop" methods can be postponed because our intended usage of Clipper involves keeping the history around.
